### ISSUE TITLE
Feature Request: Font Selection

### ISSUE THREAD

**Issue by zombiezen** [jparyani/sandstorm-simple-rich-text#2]
It would be nice to be able to pick from serif, sans-serif, and monospace at the very least, or perhaps even be able to upload your own fonts.

Icing on the cake would being able to highlight or change text colors.

**Comment by jparyani** [comment]
Turns out this was really easy since Quilljs supports all of these features :)

You can check out the new version at https://apps.sandstorm.io or wait for the autoupdate notification.
